version: "3.8"

services:
  agri-app:
    container_name: agri-app
    restart: unless-stopped
    build:
      context: .
    ports:
      - "127.0.0.1:8000:5005" # Asumsi gunicorn lo nge-serve di port 5005 dalem container
    networks:
      - agri_network
    volumes:
      - /opt/agri-media:/app/media
      - /opt/agri-static:/app/static # (Opsional) Tambahin ini kalo Nginx host mau serve static files langsung
    env_file:
      - /opt/secrets/.env
    command: >
      sh -c "
        python manage.py collectstatic --no-input
        python manage.py makemigrations
        python manage.py migrate
        #python manage.py seeder
        gunicorn --config gunicorn-cfg.py config.wsgi
      "
    depends_on:
      - agri-db

  agri-db:
    container_name: agri-db
    restart: unless-stopped
    image: postgres:15-alpine # Pake alpine biar imagesize kecil & secure
    ports:
      - "127.0.0.1:5432:5432" # Strict localhost binding buat access db client dari server doang
    env_file:
      - /opt/secrets/.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      # Pake named volume buat DB biar aman dari permission error UID/GID Postgres
      - agri-postgres-data:/var/lib/postgresql/data
    networks:
      - agri_network

networks:
  agri_network:
    driver: bridge

volumes:
  agri-postgres-data:
