# Generated by Django 4.2.9 on 2026-03-09 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cropplan',
            name='crop_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.croptype'),
        ),
        migrations.AddField(
            model_name='cropplan',
            name='parcel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_plans', to='common.parcel'),
        ),
        migrations.AddField(
            model_name='asset',
            name='row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.tabrow'),
        ),
        migrations.AddField(
            model_name='asset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
