# Generated by Django 4.2.9 on 2026-03-07 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_cropplan_croptype_substance_farm_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.sheet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TabFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('STRING', 'String'), ('NUMERIC', 'Numeric'), ('DATE', 'Date')], max_length=30)),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.tab')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
