# Generated by Django 4.2.9 on 2026-03-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='culture',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='polygon',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
