# Generated by Django 4.2.9 on 2026-03-19 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_parcel_culture_parcel_info_parcel_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropplan',
            name='parcel',
        ),
        migrations.RemoveField(
            model_name='parcel',
            name='polygon',
        ),
        migrations.CreateModel(
            name='ParcelPolygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('polygon', models.JSONField()),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.parcel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cropplan',
            name='parcel_polygon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='crop_plans', to='common.parcelpolygon'),
            preserve_default=False,
        ),
    ]
