# Generated by Django 4.2.9 on 2026-03-24 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0006_remove_cropplan_parcel_remove_parcel_polygon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
