# Generated by Django 4.2.9 on 2026-03-26 15:22

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_farm_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='info',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SheetFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='sheet')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.sheet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
