# Generated by Django 4.2.9 on 2026-03-27 15:49

import apps.common.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0008_sheet_info_sheetfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheet',
            name='farm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.farm'),
        ),
        migrations.AddField(
            model_name='sheet',
            name='state',
            field=models.CharField(choices=[('OPEN', 'Open'), ('REVIEW_NEEDED', 'Review needed'), ('APPROVED', 'Approved')], default='OPEN', max_length=20),
        ),
        migrations.AddField(
            model_name='sheet',
            name='year',
            field=models.CharField(default=apps.common.models.current_year, max_length=5),
        ),
        migrations.CreateModel(
            name='SheetChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField()),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.sheet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
