# Generated by Django 4.2.9 on 2026-03-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('FARMER', 'Farmer'), ('ENGINEER', 'Engineer'), ('EXECUTIVE', 'Executive'), ('LOGISTIC', 'Logistic'), ('AUDITOR', 'Auditor'), ('BUYER', 'Buyer')], max_length=50, null=True),
        ),
    ]
