# Generated by Django 4.2.9 on 2025-06-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_info', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.FloatField()),
                ('technology', models.CharField(choices=[('FLOWBITE', 'Flowbite'), ('REACT', 'React'), ('ANGULAR', 'Angular'), ('VUE', 'Vue')], max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('discount', models.CharField(choices=[('NO', 'No'), ('FIVE', '5%'), ('TEN', '10%'), ('TWENTY', '20%'), ('THIRTY', '30%'), ('FOURTY', '40%'), ('FIFTY', '50%')], max_length=50)),
            ],
        ),
    ]
